//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.PinyinConvert {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://khanhphong.net/", ConfigurationName="PinyinConvert.ConvertSoap")]
    public interface ConvertSoap {
        
        // CODEGEN: Generating message contract since element name PinyinWithNumber from namespace https://khanhphong.net/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="https://khanhphong.net/ToPinyinWithMark", ReplyAction="*")]
        Test.PinyinConvert.ToPinyinWithMarkResponse ToPinyinWithMark(Test.PinyinConvert.ToPinyinWithMarkRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://khanhphong.net/ToPinyinWithMark", ReplyAction="*")]
        System.Threading.Tasks.Task<Test.PinyinConvert.ToPinyinWithMarkResponse> ToPinyinWithMarkAsync(Test.PinyinConvert.ToPinyinWithMarkRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ToPinyinWithMarkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ToPinyinWithMark", Namespace="https://khanhphong.net/", Order=0)]
        public Test.PinyinConvert.ToPinyinWithMarkRequestBody Body;
        
        public ToPinyinWithMarkRequest() {
        }
        
        public ToPinyinWithMarkRequest(Test.PinyinConvert.ToPinyinWithMarkRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://khanhphong.net/")]
    public partial class ToPinyinWithMarkRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PinyinWithNumber;
        
        public ToPinyinWithMarkRequestBody() {
        }
        
        public ToPinyinWithMarkRequestBody(string PinyinWithNumber) {
            this.PinyinWithNumber = PinyinWithNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ToPinyinWithMarkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ToPinyinWithMarkResponse", Namespace="https://khanhphong.net/", Order=0)]
        public Test.PinyinConvert.ToPinyinWithMarkResponseBody Body;
        
        public ToPinyinWithMarkResponse() {
        }
        
        public ToPinyinWithMarkResponse(Test.PinyinConvert.ToPinyinWithMarkResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://khanhphong.net/")]
    public partial class ToPinyinWithMarkResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ToPinyinWithMarkResult;
        
        public ToPinyinWithMarkResponseBody() {
        }
        
        public ToPinyinWithMarkResponseBody(string ToPinyinWithMarkResult) {
            this.ToPinyinWithMarkResult = ToPinyinWithMarkResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConvertSoapChannel : Test.PinyinConvert.ConvertSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConvertSoapClient : System.ServiceModel.ClientBase<Test.PinyinConvert.ConvertSoap>, Test.PinyinConvert.ConvertSoap {
        
        public ConvertSoapClient() {
        }
        
        public ConvertSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConvertSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConvertSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConvertSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.PinyinConvert.ToPinyinWithMarkResponse Test.PinyinConvert.ConvertSoap.ToPinyinWithMark(Test.PinyinConvert.ToPinyinWithMarkRequest request) {
            return base.Channel.ToPinyinWithMark(request);
        }
        
        public string ToPinyinWithMark(string PinyinWithNumber) {
            Test.PinyinConvert.ToPinyinWithMarkRequest inValue = new Test.PinyinConvert.ToPinyinWithMarkRequest();
            inValue.Body = new Test.PinyinConvert.ToPinyinWithMarkRequestBody();
            inValue.Body.PinyinWithNumber = PinyinWithNumber;
            Test.PinyinConvert.ToPinyinWithMarkResponse retVal = ((Test.PinyinConvert.ConvertSoap)(this)).ToPinyinWithMark(inValue);
            return retVal.Body.ToPinyinWithMarkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Test.PinyinConvert.ToPinyinWithMarkResponse> Test.PinyinConvert.ConvertSoap.ToPinyinWithMarkAsync(Test.PinyinConvert.ToPinyinWithMarkRequest request) {
            return base.Channel.ToPinyinWithMarkAsync(request);
        }
        
        public System.Threading.Tasks.Task<Test.PinyinConvert.ToPinyinWithMarkResponse> ToPinyinWithMarkAsync(string PinyinWithNumber) {
            Test.PinyinConvert.ToPinyinWithMarkRequest inValue = new Test.PinyinConvert.ToPinyinWithMarkRequest();
            inValue.Body = new Test.PinyinConvert.ToPinyinWithMarkRequestBody();
            inValue.Body.PinyinWithNumber = PinyinWithNumber;
            return ((Test.PinyinConvert.ConvertSoap)(this)).ToPinyinWithMarkAsync(inValue);
        }
    }
}
