//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.PinyinChinese {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://khanhphong.net/", ConfigurationName="PinyinChinese.ChineseSoap")]
    public interface ChineseSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://khanhphong.net/GetPinyinWithNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetPinyinWithNumber(string Chinese);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://khanhphong.net/GetPinyinWithNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetPinyinWithNumberAsync(string Chinese);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://khanhphong.net/GetPinyinWithMark", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetPinyinWithMark(string Chinese);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://khanhphong.net/GetPinyinWithMark", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetPinyinWithMarkAsync(string Chinese);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://khanhphong.net/GetChineseByPinyin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetChineseByPinyin(string Pinyin);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://khanhphong.net/GetChineseByPinyin", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetChineseByPinyinAsync(string Pinyin);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://khanhphong.net/GetVietnamsesByChinese", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetVietnamsesByChinese(string Chinese);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://khanhphong.net/GetVietnamsesByChinese", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetVietnamsesByChineseAsync(string Chinese);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://khanhphong.net/TranslateToVietnamese", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string TranslateToVietnamese(string ChineseText);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://khanhphong.net/TranslateToVietnamese", ReplyAction="*")]
        System.Threading.Tasks.Task<string> TranslateToVietnameseAsync(string ChineseText);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ChineseSoapChannel : Test.PinyinChinese.ChineseSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChineseSoapClient : System.ServiceModel.ClientBase<Test.PinyinChinese.ChineseSoap>, Test.PinyinChinese.ChineseSoap {
        
        public ChineseSoapClient() {
        }
        
        public ChineseSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ChineseSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChineseSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ChineseSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetPinyinWithNumber(string Chinese) {
            return base.Channel.GetPinyinWithNumber(Chinese);
        }
        
        public System.Threading.Tasks.Task<string> GetPinyinWithNumberAsync(string Chinese) {
            return base.Channel.GetPinyinWithNumberAsync(Chinese);
        }
        
        public string GetPinyinWithMark(string Chinese) {
            return base.Channel.GetPinyinWithMark(Chinese);
        }
        
        public System.Threading.Tasks.Task<string> GetPinyinWithMarkAsync(string Chinese) {
            return base.Channel.GetPinyinWithMarkAsync(Chinese);
        }
        
        public System.Data.DataTable GetChineseByPinyin(string Pinyin) {
            return base.Channel.GetChineseByPinyin(Pinyin);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetChineseByPinyinAsync(string Pinyin) {
            return base.Channel.GetChineseByPinyinAsync(Pinyin);
        }
        
        public string GetVietnamsesByChinese(string Chinese) {
            return base.Channel.GetVietnamsesByChinese(Chinese);
        }
        
        public System.Threading.Tasks.Task<string> GetVietnamsesByChineseAsync(string Chinese) {
            return base.Channel.GetVietnamsesByChineseAsync(Chinese);
        }
        
        public string TranslateToVietnamese(string ChineseText) {
            return base.Channel.TranslateToVietnamese(ChineseText);
        }
        
        public System.Threading.Tasks.Task<string> TranslateToVietnameseAsync(string ChineseText) {
            return base.Channel.TranslateToVietnameseAsync(ChineseText);
        }
    }
}
